### ISSUE TITLE
Correct SQL requirements for bird density: use avg_vertical_integrated_density

### ISSUE THREAD

**Issue by peterdesmet** [enram/bird-migration-flow-visualization#106]
The conditions for avg_bird_density are currently:

```SQL
    CASE
        WHEN avg(b.radial_velocity_std) >= 2 AND avg(b.bird_density) >= 10 THEN round(avg(b.bird_density)::numeric,5)
        ELSE 0
    END AS avg_bird_density
```

But those WHEN requirements should actually be stated per altitude and radar, not on the average.

* [x] Have requirements per radar
* [ ] Have requirements per altitude ***across all altitude bands***
* [x] If met, take average density (for time interval) divided by 5 for that altitude. If not met set 0.
* [ ] **Sum** all those densities and call it `avg_vertical_integrated_density`

**Comment by peterdesmet** [comment]
@hvangasteren, @jshamoun two questions:

1. Can you explain why we are aggregating this for the whole altitude range and not for altitude bands?
2. Since time is aggregated per 20 minutes, more than one 5-min data point will be included: what should be done with the sum? Take the whole sum over the 20 minutes OR divide the sum by the number of data points?

**Comment by hvangasteren** [comment]
@peterdesmet Not sure what you mean with 1, but you probably mean the conditions above? 
In our vallidation of the weather radar altitude profiles with dedicated bird radars it appears that  a standard deviation of the fit larger than 2, showed a significant proportion of bird related measurement, compared to lower standard deviatons (weather and insects). Based on this starting point as well as knowing that bird migration is not evenly distributed allong all altitude bands, you through away data if you average on all altitude bands instead of selecting those altitude bands with a standard deviation larger than 2. The bird density level larger than 1 bird/km3 is used to discriminate between wind related versus bird related speeds and direction. At low densities the speed and direction could be dominated by wind.

Ad 2. Both options are OK with me, since the result is the same. Choose the easiest way.

**Comment by peterdesmet** [comment]
@hvangasteren, I'll clarify my question tomorrow. :smile:

**Comment by peterdesmet** [comment]
Was discussed. It was decided to:

1. Take average bird density **per altitude band**
2. To calculate a vid based on that average, so it could be calculated in the same query.

Query has been [described](https://github.com/enram/bird-migration-flow-visualization/blob/master/data/2013-nl-be/README.md).
